import { User } from '../types/User';

export const initialUsers: User[] = [
  { id: 1, name: 'Yunus Yavuzhan Afşar', email: 'yavuz55@example.com' },
  { id: 2, name: 'Okan Yıldırım', email: 'okan11@example.com' },
  { id: 3, name: 'Yusuf Demirci', email: 'yusuf34@example.com' },
  { id: 4, name: 'Esra Yaman', email: 'esra26@example.com' },
  { id: 5, name: 'Ali Ermiş Yıldız', email: 'alier15@example.com' },
  { id: 6, name: 'Samet Pekdemir', email: 'samet38@example.com' },
  { id: 7, name: 'Ayhan Akman', email: 'ayhan45@example.com' },
  { id: 8, name: 'Selim Yılmaz', email: 'selim13@example.com' },
  { id: 9, name: 'Berat Demir', email: 'beratdemir2@example.com' },
  { id: 10, name: 'Canan Aydın', email: 'canaydin1@example.com' },
  { id: 11, name: 'Elif Yardımlı', email: 'mail125@example.com' },
  { id: 12, name: 'Can Selim Aktürk', email: 'mail126@example.com' },
  { id: 13, name: 'Merve Yıldız', email: 'merve1@example.com' },
  { id: 14, name: 'Ahmet Kaya', email: 'ahmetk@example.com' },
  { id: 15, name: 'Gülşen Demir', email: 'gulsend@example.com' },
  { id: 16, name: 'Kadir Çetin', email: 'kadirc@example.com' },
  { id: 17, name: 'Zeynep Uçar', email: 'zeynepu@example.com' },
  { id: 18, name: 'Deniz Avcı', email: 'deniza@example.com' },
  { id: 19, name: 'Barış Şahin', email: 'bariss@example.com' },
  { id: 20, name: 'Pelin Koç', email: 'pelink@example.com' },
  { id: 21, name: 'Onur Arslan', email: 'onura@example.com' },
  { id: 22, name: 'Sena Demirtaş', email: 'senad@example.com' },
  { id: 23, name: 'Serkan Yılmaz', email: 'serkany@example.com' },
  { id: 24, name: 'Fatma Eren', email: 'fatmae@example.com' },
  { id: 25, name: 'Burak Özkan', email: 'burako@example.com' },
  { id: 26, name: 'Büşra Aydın', email: 'busraa@example.com' },
  { id: 27, name: 'Efe Çelik', email: 'efec@example.com' },
  { id: 28, name: 'İlayda Karaca', email: 'ilaydak@example.com' },
  { id: 29, name: 'Mustafa Polat', email: 'mustafap@example.com' },
  { id: 30, name: 'Derya Taş', email: 'deryat@example.com' },
  { id: 31, name: 'Volkan Özdemir', email: 'volkano@example.com' },
  { id: 32, name: 'Ayşe Nur Kılıç', email: 'aysek@example.com' },
  { id: 33, name: 'Mert Kılıç', email: 'mertk@example.com' },
  { id: 34, name: 'Zeliha Kurt', email: 'zelihak@example.com' },
  { id: 35, name: 'Arda Yavuz', email: 'arday@example.com' },
  { id: 36, name: 'Hazal Yılmaz', email: 'hazaly@example.com' },
  { id: 37, name: 'Tolga Şimşek', email: 'tolgas@example.com' },
  { id: 38, name: 'Nisa Demir', email: 'nisad@example.com' },
  { id: 39, name: 'Furkan Özkan', email: 'furkano@example.com' },
  { id: 40, name: 'Simge Yıldırım', email: 'simgey@example.com' },
  { id: 41, name: 'Bora Kaya', email: 'borak@example.com' },
  { id: 42, name: 'Sibel Avcı', email: 'sibela@example.com' },
  { id: 43, name: 'Kerem Arslan', email: 'kerema@example.com' },
  { id: 44, name: 'Hande Yıldız', email: 'handey@example.com' },
  { id: 45, name: 'Yasemin Eren', email: 'yasemine@example.com' },
  { id: 46, name: 'Ozan Aksoy', email: 'ozana@example.com' },
  { id: 47, name: 'Sevgi Koç', email: 'sevgik@example.com' },
  { id: 48, name: 'İbrahim Uçar', email: 'ibrahimu@example.com' },
  { id: 49, name: 'Betül Demirtaş', email: 'betuld@example.com' },
  { id: 50, name: 'Tunahan Çelik', email: 'tunahanc@example.com' },
  { id: 51, name: 'Gizem Yılmaz', email: 'gizemy@example.com' },
  { id: 52, name: 'Hüseyin Yavuz', email: 'huseyiny@example.com' },
  { id: 53, name: 'Beyza Demir', email: 'beyzad@example.com' },
  { id: 54, name: 'Cemre Özkan', email: 'cemreo@example.com' },
  { id: 55, name: 'Alperen Yıldırım', email: 'alpereny@example.com' },
  { id: 56, name: 'Zuhal Avcı', email: 'zuhala@example.com' },
  { id: 57, name: 'Ömer Faruk Polat', email: 'omerfp@example.com' },
  { id: 58, name: 'Büşra Kurt', email: 'busurak@example.com' },
  { id: 59, name: 'Emir Çetin', email: 'emirc@example.com' },
  { id: 60, name: 'Nilay Karaca', email: 'nilayk@example.com' },
  { id: 61, name: 'Halil Eren', email: 'halile@example.com' },
  { id: 62, name: 'Melike Polat', email: 'melikep@example.com' },
  { id: 63, name: 'Veli Taş', email: 'velit@example.com' },
  { id: 64, name: 'Tuğba Özdemir', email: 'tugbao@example.com' },
  { id: 65, name: 'Mehmet Nur Kılıç', email: 'mehmetk@example.com' },
  { id: 66, name: 'Ceren Kılıç', email: 'cerenk@example.com' },
  { id: 67, name: 'Tolga Kurt', email: 'tolgak@example.com' },
  { id: 68, name: 'Sude Yavuz', email: 'sudey@example.com' },
  { id: 69, name: 'Alparslan Demir', email: 'alparsland@example.com' },
  { id: 70, name: 'Damla Özkan', email: 'damlao@example.com' },
  
  
];
